# Generated by Django 4.2 on 2024-03-21 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0002_consultanchyservice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConsultanchyService',
            new_name='ConsultancyService',
        ),
    ]
