# Generated by Django 4.2 on 2024-03-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0003_rename_consultanchyservice_consultancyservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='NewsRoom/')),
                ('desc', models.TextField(max_length=1000)),
            ],
        ),
    ]
