# Generated by Django 4.2 on 2024-03-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0006_client_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tools_name', models.CharField(max_length=30)),
                ('tools_logo', models.ImageField(upload_to='tools/')),
            ],
        ),
    ]
