# Generated by Django 4.2 on 2024-03-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0007_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultancyservice',
            name='icon',
            field=models.FileField(upload_to='icon/'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='slider/'),
        ),
    ]
