# Generated by Django 4.2 on 2024-03-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0008_alter_consultancyservice_icon_alter_slider_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=50)),
                ('site_logo', models.ImageField(upload_to='logo/')),
                ('favicon', models.ImageField(upload_to='favicon/')),
                ('phone', models.IntegerField(max_length=25)),
                ('email', models.EmailField(max_length=50)),
                ('linkedin', models.CharField(max_length=70)),
                ('twitter', models.CharField(max_length=70)),
                ('facebook', models.CharField(max_length=70)),
                ('instagram', models.CharField(max_length=70)),
                ('youtube', models.CharField(max_length=70)),
            ],
        ),
    ]
