# Generated by Django 4.2 on 2024-03-22 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0009_website_info'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tool',
            new_name='Technology',
        ),
    ]
