# Generated by Django 4.2 on 2024-03-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0011_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='internStudent',
            field=models.BooleanField(default=False),
        ),
    ]
