# Generated by Django 4.2 on 2024-03-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0012_gallery_internstudent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.AddField(
            model_name='partner',
            name='is_only_client',
            field=models.BooleanField(default=False),
        ),
    ]
