# Generated by Django 4.2 on 2024-03-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0014_social_media_remove_website_info_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='social_media',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
