# Generated by Django 4.2 on 2024-03-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0015_social_media_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website_info',
            name='phone',
            field=models.CharField(max_length=25),
        ),
    ]
