# Generated by Django 4.2 on 2024-03-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0016_alter_website_info_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='website_info',
            name='about_of_company',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website_info',
            name='developed_year',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
