# Generated by Django 4.2 on 2024-03-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0017_website_info_about_of_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website_Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_page_title', models.CharField(max_length=30)),
                ('services_section_title', models.CharField(max_length=60)),
                ('services_section_title2', models.CharField(max_length=60)),
                ('services_section_title3', models.CharField(max_length=60)),
                ('client_section_title', models.CharField(max_length=60)),
                ('partner_section_title', models.CharField(max_length=60)),
                ('partner_page_title', models.CharField(max_length=60)),
                ('partner_page_banner', models.ImageField(upload_to='banner/')),
                ('footer_section_title', models.CharField(max_length=30)),
                ('office_section_title', models.CharField(max_length=30)),
                ('about_page_title', models.CharField(max_length=30)),
                ('about_page_banner', models.ImageField(upload_to='banner/')),
                ('career_page_title', models.CharField(max_length=30)),
                ('career_page_banner', models.ImageField(upload_to='banner/')),
                ('contact_page_title', models.CharField(max_length=30)),
                ('contact_page_banner', models.ImageField(upload_to='banner/')),
                ('news_page_title', models.CharField(max_length=30)),
                ('news_page_banner', models.ImageField(upload_to='banner/')),
            ],
        ),
    ]
