# Generated by Django 4.2 on 2024-03-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0018_website_setting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Website_Info',
        ),
        migrations.AddField(
            model_name='website_setting',
            name='about_of_company',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website_setting',
            name='capabilitis_section_banner',
            field=models.ImageField(default=1, upload_to='banner/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website_setting',
            name='capabilitis_section_title',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website_setting',
            name='developed_year',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website_setting',
            name='email',
            field=models.EmailField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website_setting',
            name='favicon',
            field=models.ImageField(default=1, upload_to='favicon/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website_setting',
            name='mission_desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website_setting',
            name='mission_image',
            field=models.ImageField(default=1, upload_to='img/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website_setting',
            name='mission_title',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website_setting',
            name='phone',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website_setting',
            name='site_logo',
            field=models.ImageField(default=1, upload_to='logo/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website_setting',
            name='site_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website_setting',
            name='vision_and_mission_section_banner',
            field=models.ImageField(default=1, upload_to='banner/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website_setting',
            name='vision_desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website_setting',
            name='vision_image',
            field=models.ImageField(default=1, upload_to='img/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website_setting',
            name='vision_title',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
