# Generated by Django 4.2 on 2024-03-24 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0023_alter_newsroom_image_2_alter_newsroom_image_3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsroom',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='newsroom',
            name='image_3',
        ),
    ]
