# Generated by Django 4.2 on 2024-03-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0024_remove_newsroom_image_2_remove_newsroom_image_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsroom',
            name='image_2',
            field=models.ImageField(default=1, upload_to='NewsRoom/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsroom',
            name='image_3',
            field=models.ImageField(default=1, upload_to='NewsRoom/'),
            preserve_default=False,
        ),
    ]
