# Generated by Django 4.2 on 2024-03-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0025_newsroom_image_2_newsroom_image_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsroom',
            name='desc',
            field=models.TextField(max_length=500),
        ),
    ]
