# Generated by Django 4.2 on 2024-03-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0028_alter_newsroom_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsroom',
            name='desc',
            field=models.TextField(max_length=300),
        ),
    ]
