# Generated by Django 4.2 on 2024-03-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0029_alter_newsroom_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='website_setting',
            name='technology_page_title',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
