# Generated by Django 4.2 on 2024-03-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0030_website_setting_technology_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='website_setting',
            name='gallery_page_title',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website_setting',
            name='gallery_section_title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
