# Generated by Django 4.2 on 2024-03-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0033_rename_career_page_banner_website_setting_career_page_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website_setting',
            name='career_page_image_3',
            field=models.ImageField(default=1, upload_to='banner/'),
            preserve_default=False,
        ),
    ]
