# Generated by Django 4.2 on 2024-03-24 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0035_career'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='email',
            field=models.EmailField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='file',
            field=models.FileField(upload_to='cv/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx0'])]),
        ),
    ]
