# Generated by Django 4.2 on 2024-03-24 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0036_alter_career_email_alter_career_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='file',
            field=models.FileField(upload_to='cv/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
