# Generated by Django 4.2 on 2024-03-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0037_alter_career_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='file',
            field=models.FileField(upload_to='cv/'),
        ),
    ]
