# Generated by Django 4.2 on 2024-03-24 16:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0038_alter_career_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('title', models.CharField(max_length=40)),
                ('academic_qualification', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('desc', ckeditor.fields.RichTextField()),
                ('is_ceo', models.BooleanField(default=False)),
                ('is_management_team_member', models.BooleanField(default=False)),
                ('is_development_team_leader', models.BooleanField(default=False)),
                ('is_development_team_member', models.BooleanField(default=False)),
            ],
        ),
    ]
