# Generated by Django 4.2 on 2024-03-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0039_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='website_setting',
            name='team_page_banner',
            field=models.ImageField(default=1, upload_to='banner/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website_setting',
            name='team_page_title',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
