# Generated by Django 4.2 on 2024-03-25 08:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0042_website_setting_expertise_of_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='website_setting',
            name='business_solution_section_desc',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website_setting',
            name='business_solution_section_image',
            field=models.ImageField(default=1, upload_to='img/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website_setting',
            name='business_solution_section_title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website_setting',
            name='professionals_of_company',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website_setting',
            name='why_us_page_banner',
            field=models.ImageField(default=1, upload_to='', verbose_name='banner/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website_setting',
            name='why_us_page_title',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
