# Generated by Django 4.2 on 2024-03-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0043_website_setting_business_solution_section_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website_setting',
            name='why_us_page_banner',
            field=models.ImageField(upload_to='banner/'),
        ),
    ]
