# Generated by Django 4.2 on 2024-03-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0044_alter_website_setting_why_us_page_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChoseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='why-us/')),
                ('is_important', models.BooleanField(default=False)),
            ],
        ),
    ]
