# Generated by Django 4.2 on 2024-03-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0045_whychoseus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website_setting',
            old_name='professionals_of_company',
            new_name='profession_of_company',
        ),
        migrations.AddField(
            model_name='website_setting',
            name='profession_section_banner',
            field=models.ImageField(default=1, upload_to='banner/'),
            preserve_default=False,
        ),
    ]
