# Generated by Django 4.2 on 2024-03-25 15:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0047_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='detail',
            field=ckeditor.fields.RichTextField(max_length=600),
        ),
    ]
