# Generated by Django 4.2 on 2024-03-25 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0048_alter_office_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='country',
            new_name='country_base_office',
        ),
    ]
