# Generated by Django 4.2 on 2024-03-25 19:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0049_rename_country_office_country_base_office'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('cover_photo', models.FileField(upload_to='service/')),
                ('icon', models.FileField(upload_to='service/')),
                ('desc', models.TextField()),
                ('image', models.ImageField(upload_to='services')),
                ('image_2', models.ImageField(upload_to='service')),
                ('section_title', models.CharField(max_length=200)),
                ('learning_objective', ckeditor.fields.RichTextField()),
                ('image_3', models.ImageField(upload_to='service/')),
                ('image_4', models.ImageField(upload_to='service/')),
                ('more', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
