# Generated by Django 4.2 on 2024-03-25 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0050_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_device_based',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='is_software_based',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('icon', models.FileField(upload_to='feature')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osit.service')),
            ],
        ),
    ]
