# Generated by Django 4.2 on 2024-03-25 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0051_service_is_device_based_service_is_software_based_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='section_title',
            new_name='feature_title',
        ),
    ]
