# Generated by Django 4.2 on 2024-03-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0052_rename_section_title_service_feature_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image_2',
            field=models.FileField(upload_to='service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_3',
            field=models.FileField(upload_to='service/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_4',
            field=models.FileField(upload_to='service/'),
        ),
    ]
