# Generated by Django 4.2 on 2024-03-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0053_alter_service_image_2_alter_service_image_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='google_map_link',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
