# Generated by Django 4.2 on 2024-03-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0054_office_google_map_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
            ],
        ),
    ]
