# Generated by Django 4.2 on 2024-03-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0055_companyquality'),
    ]

    operations = [
        migrations.AddField(
            model_name='website_setting',
            name='technology_icon',
            field=models.FileField(default=1, upload_to='icon/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='career',
            name='email',
            field=models.EmailField(max_length=60),
        ),
    ]
