# Generated by Django 4.2 on 2024-03-27 08:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0057_alter_career_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_page_title', models.CharField(max_length=30)),
                ('about_page_banner', models.ImageField(upload_to='banner/')),
                ('about_of_company', models.TextField()),
                ('expertise_of_company', ckeditor.fields.RichTextField()),
                ('profession_of_company', ckeditor.fields.RichTextField()),
                ('profession_section_banner', models.ImageField(upload_to='banner/')),
                ('vision_and_mission_section_banner', models.ImageField(upload_to='banner/')),
                ('vision_title', models.CharField(max_length=20)),
                ('vision_image', models.ImageField(upload_to='img/')),
                ('vision_desc', models.TextField()),
                ('mission_title', models.CharField(max_length=20)),
                ('mission_image', models.ImageField(upload_to='img/')),
                ('mission_desc', models.TextField()),
                ('capabilities_section_title', models.CharField(max_length=30)),
                ('capabilities_section_banner', models.ImageField(upload_to='banner/')),
            ],
        ),
        migrations.RemoveField(
            model_name='website_setting',
            name='about_of_company',
        ),
        migrations.RemoveField(
            model_name='website_setting',
            name='about_page_banner',
        ),
        migrations.RemoveField(
            model_name='website_setting',
            name='about_page_title',
        ),
        migrations.RemoveField(
            model_name='website_setting',
            name='capabilities_section_banner',
        ),
        migrations.RemoveField(
            model_name='website_setting',
            name='capabilities_section_title',
        ),
        migrations.RemoveField(
            model_name='website_setting',
            name='expertise_of_company',
        ),
        migrations.RemoveField(
            model_name='website_setting',
            name='mission_desc',
        ),
        migrations.RemoveField(
            model_name='website_setting',
            name='mission_image',
        ),
        migrations.RemoveField(
            model_name='website_setting',
            name='mission_title',
        ),
        migrations.RemoveField(
            model_name='website_setting',
            name='profession_of_company',
        ),
        migrations.RemoveField(
            model_name='website_setting',
            name='profession_section_banner',
        ),
        migrations.RemoveField(
            model_name='website_setting',
            name='vision_and_mission_section_banner',
        ),
        migrations.RemoveField(
            model_name='website_setting',
            name='vision_desc',
        ),
        migrations.RemoveField(
            model_name='website_setting',
            name='vision_image',
        ),
        migrations.RemoveField(
            model_name='website_setting',
            name='vision_title',
        ),
    ]
