# Generated by Django 4.2 on 2024-03-27 08:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0058_aboutpagesetting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpagesetting',
            name='profession_of_company',
        ),
        migrations.RemoveField(
            model_name='aboutpagesetting',
            name='profession_section_banner',
        ),
        migrations.AddField(
            model_name='website_setting',
            name='profession_of_company',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website_setting',
            name='profession_section_banner',
            field=models.ImageField(default=1, upload_to='banner/'),
            preserve_default=False,
        ),
    ]
