# Generated by Django 4.2 on 2024-03-27 09:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0059_remove_aboutpagesetting_profession_of_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChoseUsPageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('why_us_page_title', models.CharField(max_length=30)),
                ('why_us_page_banner', models.ImageField(upload_to='banner/')),
                ('business_solution_section_title', models.CharField(max_length=100)),
                ('business_solution_section_desc', models.TextField(max_length=500)),
                ('business_solution_section_image', models.ImageField(upload_to='img/')),
                ('profession_of_company', ckeditor.fields.RichTextField()),
                ('profession_section_banner', models.ImageField(upload_to='banner/')),
            ],
        ),
        migrations.RemoveField(
            model_name='website_setting',
            name='business_solution_section_desc',
        ),
        migrations.RemoveField(
            model_name='website_setting',
            name='business_solution_section_image',
        ),
        migrations.RemoveField(
            model_name='website_setting',
            name='business_solution_section_title',
        ),
        migrations.RemoveField(
            model_name='website_setting',
            name='profession_of_company',
        ),
        migrations.RemoveField(
            model_name='website_setting',
            name='profession_section_banner',
        ),
        migrations.RemoveField(
            model_name='website_setting',
            name='why_us_page_banner',
        ),
        migrations.RemoveField(
            model_name='website_setting',
            name='why_us_page_title',
        ),
    ]
