# Generated by Django 4.2 on 2024-03-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0060_whychoseuspagesetting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whychoseuspagesetting',
            name='values_section_title',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
