# Generated by Django 4.2 on 2024-03-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0062_website_setting_technology_page_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='website_setting',
            name='partner_icon',
            field=models.FileField(default=1, upload_to='icon/'),
            preserve_default=False,
        ),
    ]
