# Generated by Django 4.2 on 2024-03-29 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0063_website_setting_partner_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='career',
            old_name='file',
            new_name='cv',
        ),
    ]
