# Generated by Django 4.2 on 2024-04-01 07:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0064_rename_file_career_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='feature_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_2',
            field=models.FileField(blank=True, null=True, upload_to='service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_3',
            field=models.FileField(blank=True, null=True, upload_to='service/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_4',
            field=models.FileField(blank=True, null=True, upload_to='service/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='learning_objective',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='more',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
