# Generated by Django 4.2 on 2024-04-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0065_alter_service_feature_title_alter_service_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_2',
            field=models.FileField(blank=True, null=True, upload_to='service/'),
        ),
    ]
