# Generated by Django 4.2 on 2024-04-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0066_alter_service_image_alter_service_image_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='services/'),
        ),
    ]
