# Generated by Django 4.2 on 2024-04-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0067_alter_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='feature_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
