# Generated by Django 4.2 on 2024-04-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0069_alter_service_feature_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.FileField(default=None, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_2',
            field=models.FileField(default=None, upload_to='service/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_3',
            field=models.FileField(default=None, upload_to='service/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_4',
            field=models.FileField(default=None, upload_to='service/'),
        ),
    ]
