# Generated by Django 4.2 on 2024-04-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0073_alter_service_image_alter_service_image_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='feature_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
