# Generated by Django 4.2 on 2024-04-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0077_alter_newsroom_image_2_alter_newsroom_image_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
