# Generated by Django 4.2 on 2024-04-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0078_teammember_is_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
