# Generated by Django 4.2 on 2024-04-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0080_slider_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='is_ui_team_member',
            field=models.BooleanField(default=False),
        ),
    ]
