# Generated by Django 4.2 on 2024-04-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0081_teammember_is_ui_team_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='is_digital_marketing_team',
            field=models.BooleanField(default=False),
        ),
    ]
