# Generated by Django 4.2 on 2024-04-30 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0082_teammember_is_digital_marketing_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='is_digital_marketing_team',
            new_name='is_digital_marketing_team_member',
        ),
    ]
