# Generated by Django 4.2 on 2024-05-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0083_rename_is_digital_marketing_team_teammember_is_digital_marketing_team_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('logo', models.ImageField(upload_to='membership/')),
            ],
        ),
    ]
