# Generated by Django 4.2 on 2024-05-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0085_newsroom_job_fair_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsroom',
            name='Support_Activity',
            field=models.BooleanField(default=False),
        ),
    ]
