# Generated by Django 4.2 on 2024-05-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0086_newsroom_support_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsroom',
            name='desc',
            field=models.TextField(),
        ),
    ]
