# Generated by Django 4.2 on 2024-05-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0087_alter_newsroom_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsroom',
            name='desc',
            field=models.TextField(max_length=300),
        ),
    ]
