# Generated by Django 4.2 on 2024-05-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0088_alter_newsroom_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award_And_Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='certificate/')),
            ],
        ),
    ]
