# Generated by Django 4.2 on 2024-05-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0089_award_and_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='website_setting',
            name='award_section_title',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
