# Generated by Django 4.2 on 2024-05-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0090_website_setting_award_section_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsroom',
            name='desc',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
