# Generated by Django 4.2 on 2024-05-04 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0091_alter_newsroom_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='is_hr_team',
            field=models.BooleanField(default=False),
        ),
    ]
