# Generated by Django 4.2 on 2024-05-04 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0092_teammember_is_hr_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='is_hr_team',
            new_name='is_hr_team_member',
        ),
    ]
