# Generated by Django 4.2 on 2024-05-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0093_rename_is_hr_team_teammember_is_hr_team_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsroom',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
