# Generated by Django 4.2 on 2024-05-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0096_alter_newsroom_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsroom',
            name='timestamp',
            field=models.DateField(auto_now=True),
        ),
    ]
