# Generated by Django 4.2 on 2024-05-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0097_alter_newsroom_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
