# Generated by Django 4.2 on 2024-05-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0099_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website_setting',
            name='award_section_title',
        ),
        migrations.AddField(
            model_name='aboutpagesetting',
            name='award_section_title',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutpagesetting',
            name='video_section_title',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
