# Generated by Django 4.2 on 2024-05-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osit', '0100_remove_website_setting_award_section_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='link',
            field=models.URLField(),
        ),
    ]
